const throwException = () => {
    throw new Error('Intentional error thrown');
  };
  
  module.exports = throwException;